#!/usr/bin/env python3

"""
Data used for producing the display values of geographic facets in radiosearch
"""

STATE_PREFIXES = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CA": "California",
    "CT": "Connecticut",
    "CO": "Colorado",
    "DC": "District of Columbia",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IA": "Iowa",
    "IN": "Indiana",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "NH": "New Hampshire",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MN": "Minnesota",
    "ME": "Maine",
    "MI": "Michigan",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NJ": "New Jersey",
    "NE": "Nebraska",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VA": "Virginia",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming",
    "VT": "Vermont",
    "ONT": "Ontario",
    "QUE": "Quebec",
    "AB": "Alberta",
    "SK": "Saskatchewan",
    "BC": "British Columbia",
    "MB": "Manitoba",
    "NS": "Nova Scotia",
}
