/*
 * Radio-Twitter link tables not created by twclient scripts
 */

drop table if exists twitter.user_show;
create table twitter.user_show
(
    user_show_id bigint
        generated by default as identity
        primary key,

    user_id bigint
        not null
        references twitter.user
        deferrable initially immediate,

    show_id bigint
        not null
        references radio.show
        deferrable initially immediate,

    is_host boolean not null default false,
    is_show boolean not null default false,

    insert_dt timestamptz not null default now(),

    unique (user_id, show_id) deferrable initially immediate
);

