/*
 * Election results data tables
 */

drop table if exists election.precinct_results_2016;
create unlogged table election.precinct_results_2016
(
    precinct_id int not null
        generated by default as identity
        primary key,

    state_id int not null
        references dim.state
        deferrable initially immediate,

    votes_pres_dem int not null,
    votes_pres_rep int not null,
    votes_pres_total int not null,

    wkt text not null
);

