/*
 * Census data
 */

drop table if exists census.survey cascade;
create table census.survey
(
    survey_id int
        generated by default as identity
        primary key,

    name text not null,
    is_census boolean not null,
    year int not null,

    unique(name) deferrable initially immediate
);

drop table if exists census.variable cascade;
create table census.variable
(
    variable_id int
        generated by default as identity
        primary key,

    name text not null,

    description text,

    unique(name) deferrable initially immediate
);

drop table if exists census.geography cascade;
create table census.geography
(
    geography_id bigint
        generated by default as identity
        primary key,

    defining_survey_id int not null
        references census.survey
        deferrable initially immediate,

    -- the longest possible geoid is 22 characters, of the form
    -- XXXXX + US + state_fips + county_fips + tract_code + bg_code + block_code
    geoid varchar(22) not null,

    name text not null,
    state_fips text,
    county_fips text,
    tract_code text,
    block_group_code text,
    land_area text,
    water_area text,
    wkt text,

    unique(defining_survey_id, geoid) deferrable initially immediate
);

drop table if exists census.data cascade;
create table census.data
(
    survey_id int not null
        references census.survey
        deferrable initially immediate,

    geography_id int not null
        references census.geography
        deferrable initially immediate,

    variable_id int not null
        references census.variable
        deferrable initially immediate,

    value text,

    primary key (survey_id, geography_id, variable_id)
);

begin;
    insert into census.survey
        (survey_id, is_census, year, name)
    values
        (1, true, 2010, '2010 Census'),
        (2, false, 2016, '2016 ACS');
commit;

